### ISSUE TITLE
Fonts, Favicon, Icons, Missing Styles

### ISSUE THREAD

**Issue by dgading** [GetDKAN/data-catalog-react#14]
- [x] No Title in browser tab
- [x] Wrong Favicon
- [x] Missing Checkboxs on facets
- [x] wrong fonts loading
- [x] missing icon on toggle facets blocks
- [ ] display density buttons not styled properly
- [x] manage column button missing border
- [ ] fix circleci integration
- [x] pull in https://github.com/GetDKAN/data-catalog-frontend/pull/54
- [x] pull in https://github.com/GetDKAN/data-catalog-frontend/pull/49

## Merge Plan:
- [ ] merge data-catalog-components https://github.com/GetDKAN/data-catalog-components/pull/89
- [ ] publish new release of data-catalog-components
- [ ] merge dkan-tools updates https://github.com/GetDKAN/dkan-tools/pull/229
- [ ] publish new release of dkan-tools
- [ ] update package.json on this repo to use new components release
- [ ] update .circleci/config.yml on this repo to use new dkan-tools tag
- [ ] publish new release of data-catalog-react (rename repo?)
- [ ] merge dkan PR (frontend module config) https://github.com/GetDKAN/dkan/pull/3173

**Comment by janette** [comment]
also:

- [ ]     merge dkan-tools updates https://github.com/GetDKAN/dkan-tools/pull/229
- [ ]     merge data-catalog-components https://github.com/GetDKAN/data-catalog-components/pull/89
- [ ]     fix circleci integration
- [ ]     fix dkan-frontend and cypress config
- [ ]     pull in https://github.com/GetDKAN/data-catalog-frontend/pull/54
- [ ]     pull in https://github.com/GetDKAN/data-catalog-frontend/pull/49
